repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer

  - repo: https://gitee.com/mirrors_PyCQA/flake8.git
    rev: 3.8.4
    hooks:
    - id: flake8
      args:
      - --max-line-length=120 #设置代码行最大长度
      - --extend-ignore=E1,E203,E722,E402,F401,F403,F405,N803,N813,N805,N802,E501,F841 #设置忽略的警告代码
      #- --max-complexity=12   # 设置代码复杂度
      exclude: ^.*test/
      additional_dependencies:
        - "pep8-naming"
